version: '3.7'
services:
   zookeeper:
      image: wurstmeister/zookeeper
      container_name: zookeeper
      ports:
      - 2181:2181
   kafka:
      image: wurstmeister/kafka
      container_name: kafka
      depends_on:
      - "zookeeper"
      ports:
      - 9092:9092
      environment:
         KAFKA_ADVERTISED_HOST_NAME: localhost
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
   portal-service-mongodb:
      image: mongo:latest
      container_name: portal-service-mongodb
      ports:
      - 27017:27017
   authserver-mongodb:
      image: mongo:latest
      container_name: authserver-mongodb
      ports:
      - 27018:27017