server:
   port: 8081
logging:
   level:
      root: INFO
springdoc:
   swagger-ui:
      path: /phonebgidge-um-doc.html
spring:
   data:
      mongodb:
         authentication-database: admin
         database: phonebridge_usermanagement
         port: 27018
         host: localhost