server:
   port: 8081
logging:
   level:
      root: INFO
springdoc:
   swagger-ui:
      path: /phonebridge-user-management.html
spring:
   application:
      name: user-management
   data:
      mongodb:
         authentication-database: admin
         database: pb_user_management
         port: 27018
         host: localhost