server:
   port: 8081
logging:
   level:
      root: INFO
spring:
   data:
      mongodb:
         authentication-database: admin
         database: phonebridge_usermanagement
         port: 27018
         host: localhost