logging:
   level:
      root: INFO
server:
   port: 8887
management:
   endpoints:
      web:
         exposure:
            include: '*'
   security:
      enabled: false
spring:
   application:
      name: phonebridge-config-server
   boot:
      admin:
         client:
            url: http://phonebridge-admin
   kafka:
      bootstrap-servers: http://localhost:9092
   cloud:
      bus:
         enabled: true
      config:
         server:
            git:
               uri: https://github.com/Vinoth5595/phonebridge-configurations.git
               clone-on-start: true