spring:
   application:
      name: phonebridge-discovery
   boot:
      admin:
         client:
            url: http://localhost:8093
server:
   port: 8761
eureka:
   client:
      register-with-eureka: false
      fetch-registry: false
logging:
      com:
         netflix:
            eureka: false
            discovery: false
management:
   endpoints:
      web:
         exposure:
            include: '*'